import React, { ReactNode } from "react";
import "../../styles/user.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { App } from "antd";
import HeaderUser from "@/components/user/header/HeaderUser";
import FooterUser from "@/components/user/footer/FooterUser";
import Newsletter from "@/components/user/footer/Newsletter";
import Offcanva from "@/components/user/home/Offcanva";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootUserLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <>
      <AntdRegistry>
        <App>
          <main>
            <Offcanva />
            <HeaderUser />
            {children}
            <Newsletter />
            <FooterUser />
          </main>
        </App>
      </AntdRegistry>
    </>
  );
}
